rova: qcom-caf: audio: Fix compilation errors
* Regression introduced in 0f6e0653253a6a7812125e793d6f427589ad8c39.

---

device/xiaomi/rova/qcom-caf/audio/visualizer/offload_visualizer.c:450:33: error: unused parameter 'arg' [-Werror,-Wunused-parameter]
  450 | void *capture_thread_loop(void *arg)
      |                                 ^
device/xiaomi/rova/qcom-caf/audio/visualizer/offload_visualizer.c:815:85: error: unused parameter 'size' [-Werror,-Wunused-parameter]
  815 | int visualizer_set_parameter(effect_context_t *context, effect_param_t *p, uint32_t size)
      |                                                                                     ^
device/xiaomi/rova/qcom-caf/audio/visualizer/offload_visualizer.c:948:79: error: unused parameter 'cmdSize' [-Werror,-Wunused-parameter]
  948 | int visualizer_command(effect_context_t * context, uint32_t cmdCode, uint32_t cmdSize,
      |                                                                               ^
device/xiaomi/rova/qcom-caf/audio/visualizer/offload_visualizer.c:949:15: error: unused parameter 'pCmdData' [-Werror,-Wunused-parameter]
  949 |         void *pCmdData, uint32_t *replySize, void *pReplyData)
      |               ^
device/xiaomi/rova/qcom-caf/audio/visualizer/offload_visualizer.c:1085:34: error: unused parameter 'sessionId' [-Werror,-Wunused-parameter]
 1085 |                          int32_t sessionId,
      |                                  ^
device/xiaomi/rova/qcom-caf/audio/visualizer/offload_visualizer.c:1206:40: error: unused parameter 'inBuffer' [-Werror,-Wunused-parameter]
 1206 |                        audio_buffer_t *inBuffer,
      |                                        ^
device/xiaomi/rova/qcom-caf/audio/visualizer/offload_visualizer.c:1207:40: error: unused parameter 'outBuffer' [-Werror,-Wunused-parameter]
 1207 |                        audio_buffer_t *outBuffer)
      |                                        ^
7 errors generated.

---

device/xiaomi/rova/qcom-caf/audio/hal/audio_extn/cirrus_playback.c:204:17: error: incompatible function pointer types passing 'void *(void)' to parameter of type 'void * _Nullable (* _Nonnull)(void * _Nullable)' [-Wincompatible-function-pointer-types]
204 |                 audio_extn_cirrus_calibration_thread, &handle);
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bionic/libc/include/pthread.h:162:123: note: passing argument to parameter '__start_routine' here
162 | int pthread_create(pthread_t* _Nonnull __pthread_ptr, pthread_attr_t const* _Nullable __attr, void* _Nullable (* _Nonnull __start_routine)(void* _Nullable), void* _Nullable);
|                                                                                                                           ^
device/xiaomi/rova/qcom-caf/audio/hal/audio_extn/cirrus_playback.c:568:21: error: incompatible function pointer types passing 'void *(void)' to parameter of type 'void * _Nullable (* _Nonnull)(void * _Nullable)' [-Wincompatible-function-pointer-types]
568 |                     audio_extn_cirrus_failure_detect_thread,
|                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bionic/libc/include/pthread.h:162:123: note: passing argument to parameter '__start_routine' here
162 | int pthread_create(pthread_t* _Nonnull __pthread_ptr, pthread_attr_t const* _Nullable __attr, void* _Nullable (* _Nonnull __start_routine)(void* _Nullable), void* _Nullable);
|                                                                                                                           ^
device/xiaomi/rova/qcom-caf/audio/hal/audio_extn/cirrus_playback.c:888:21: error: incompatible function pointer types passing 'void *(void)' to parameter of type 'void * _Nullable (* _Nonnull)(void * _Nullable)' [-Wincompatible-function-pointer-types]
888 |                     audio_extn_cirrus_failure_detect_thread,
|                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bionic/libc/include/pthread.h:162:123: note: passing argument to parameter '__start_routine' here
162 | int pthread_create(pthread_t* _Nonnull __pthread_ptr, pthread_attr_t const* _Nullable __attr, void* _Nullable (* _Nonnull __start_routine)(void* _Nullable), void* _Nullable);
|                                                                                                                           ^
3 errors generated.

Signed-off-by: iusmac <iusico.maxim@libero.it>