rova: qcom-caf: gralloc: Remove libhidltransport deps
* libhidltransport has been combined into libhidlbase and got
  deprecated.

  error: device/xiaomi/rova/qcom-caf/display/gralloc/Android.bp:130:1: module "android.hardware.graphics.mapper@3.0-impl-qti-display" variant "android_vendor_arm64_armv8-a_cortex-a53_shared": depends on //system/libhidl:libhidltransport which is not visible to this module
  You may need to add "//device/xiaomi/rova/qcom-caf/display/gralloc" to its visibility
  error: device/xiaomi/rova/qcom-caf/display/gralloc/Android.bp:167:1: module "android.hardware.graphics.mapper@4.0-impl-qti-display" variant "android_vendor_arm64_armv8-a_cortex-a53_shared": depends on //system/libhidl:libhidltransport which is not visible to this module
  You may need to add "//device/xiaomi/rova/qcom-caf/display/gralloc" to its visibility

Signed-off-by: iusmac <iusico.maxim@libero.it>